name: Infracost

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  infracost:
    # Only post comments when the workflow is running for a PR
    if: github.event_name == 'pull_request'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          path: head

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: base

      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Infracost Diff
        uses: infracost/actions/diff@v4
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: ./base
          head-path: ./head
          github-owner: ${{ github.repository_owner }}
          github-repo: ${{ github.event.repository.name }}
          pr-number: ${{ github.event.pull_request.number }}